#!/bin/bash

node_name () {
	cat /etc/systemd/system/kubelet.service | grep hostname-override | cut -d= -f2 | cut -d' ' -f1
}

log=/var/log/cni.log
config=`cat /dev/stdin`

echo >> $log
echo "COMMAND: $CNI_COMMAND" >> $log

case $CNI_COMMAND in
ADD)
    podcidr=$(echo $config | jq -r ".podcidr")
    podcidr_gw=$(echo $podcidr | sed "s:0/24:1:g")
    brctl addbr cni0
    ip link set cni0 up
    ip addr add "${podcidr_gw}/24" dev cni0
    
    # calculate $ip
    for n in {2..254}
    do
        if ! grep "^${n}$" /tmp/allocated_ip ; then
            echo ${n} >> /tmp/allocated_ip`
            break
        fi
    done
    ip=$(echo $podcidr | sed "s:0/24:$n:g")

    mkdir -p /var/run/netns/
    ln -sfT $CNI_NETNS /var/run/netns/$CNI_CONTAINERID
    ln -sfT /proc/1/ns/net /var/run/netns/root

    host_ifname="veth$n"
    ip netns exec $CNI_CONTAINERID ip link add $CNI_IFNAME type veth peer name $host_ifname
    ip netns exec $CNI_CONTAINERID ip link set $host_ifname netns root
    ip link set $host_ifname up
    ip link set $host_ifname master cni0

    ip netns exec $CNI_CONTAINERID ip link set $CNI_IFNAME up
    ip netns exec $CNI_CONTAINERID ip addr add $ip/24 dev $CNI_IFNAME
    ip netns exec $CNI_CONTAINERID ip route add default via $podcidr_gw

    mac=$(ip netns exec $CNI_CONTAINERID ip link show eth0 | awk '/ether/ {print $2}')
    address="${ip}/24"
    output_template='
{
  "cniVersion": "0.3.1",
  "interfaces": [                                            
      {
          "name": "%s",
          "mac": "%s",                            
          "sandbox": "%s" 
      }
  ],
  "ips": [
      {
          "version": "4",
          "address": "%s",
          "gateway": "%s",          
          "interface": 0 
      }
  ]
}' 
    
    output=$(printf "${output_template}" $CNI_IFNAME $mac $CNI_NETNS $address $podcidr_gw)
    echo $output >> $log
    echo "$output"
    
;;

DEL)
    ip=$(ip netns exec $CNI_CONTAINERID ip a show eth0 | grep inet | grep eth0 | cut -d/ -f1 | cut -d. -f4)
    sed -i "/^${number}$/d" /tmp/allocated_ip
    rm -rf /var/run/netns/$CNI_CONTAINERID
;;

GET)
;;

VERSION)
echo '{
  "cniVersion": "0.3.1", 
  "supportedVersions": [ "0.3.0", "0.3.1", "0.4.0" ] 
}'
;;

*)
  echo "Unknown cni command: $CNI_COMMAND" 
  exit 1
;;

esac
